In [90]:
import jax.numpy as jnp 

a = jnp.arange(10)
b = jnp.arange(3)

grids = jnp.meshgrid(a, b, indexing="ij")   

In [116]:
sta_link = {
    (int(sta), int(link)): int(sta + link)

    for sta, link in jnp.stack([grid.ravel() for grid in grids], axis=-1)
}

In [117]:
print(sta_link)

{(0, 0): 0, (0, 1): 1, (0, 2): 2, (1, 0): 1, (1, 1): 2, (1, 2): 3, (2, 0): 2, (2, 1): 3, (2, 2): 4, (3, 0): 3, (3, 1): 4, (3, 2): 5, (4, 0): 4, (4, 1): 5, (4, 2): 6, (5, 0): 5, (5, 1): 6, (5, 2): 7, (6, 0): 6, (6, 1): 7, (6, 2): 8, (7, 0): 7, (7, 1): 8, (7, 2): 9, (8, 0): 8, (8, 1): 9, (8, 2): 10, (9, 0): 9, (9, 1): 10, (9, 2): 11}


In [112]:
sta_link[jnp.int32(3), 2]

TypeError: unhashable type: 'jaxlib._jax.ArrayImpl'

In [99]:
for s_l in jnp.stack([grid.ravel() for grid in grids], axis=-1):
    print(tuple(s_l.tolist()))

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(4, 0)
(4, 1)
(4, 2)
(5, 0)
(5, 1)
(5, 2)
(6, 0)
(6, 1)
(6, 2)
(7, 0)
(7, 1)
(7, 2)
(8, 0)
(8, 1)
(8, 2)
(9, 0)
(9, 1)
(9, 2)


In [ ]:
cartesian_product = np.stack([x.ravel() for x in grids], axis=-1)

In [ ]:
print(tuple(cartesian_product.tolist()))

([0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2], [3, 0], [3, 1], [3, 2], [4, 0], [4, 1], [4, 2], [5, 0], [5, 1], [5, 2], [6, 0], [6, 1], [6, 2], [7, 0], [7, 1], [7, 2], [8, 0], [8, 1], [8, 2], [9, 0], [9, 1], [9, 2], [10, 0], [10, 1], [10, 2], [11, 0], [11, 1], [11, 2], [12, 0], [12, 1], [12, 2], [13, 0], [13, 1], [13, 2], [14, 0], [14, 1], [14, 2], [15, 0], [15, 1], [15, 2], [16, 0], [16, 1], [16, 2], [17, 0], [17, 1], [17, 2], [18, 0], [18, 1], [18, 2], [19, 0], [19, 1], [19, 2])


In [ ]:
print(grids)

(array([[ 0,  0,  0],
       [ 1,  1,  1],
       [ 2,  2,  2],
       [ 3,  3,  3],
       [ 4,  4,  4],
       [ 5,  5,  5],
       [ 6,  6,  6],
       [ 7,  7,  7],
       [ 8,  8,  8],
       [ 9,  9,  9],
       [10, 10, 10],
       [11, 11, 11],
       [12, 12, 12],
       [13, 13, 13],
       [14, 14, 14],
       [15, 15, 15],
       [16, 16, 16],
       [17, 17, 17],
       [18, 18, 18],
       [19, 19, 19]]), array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]]))


In [121]:
import numpy as np 
from chex import Array 

In [123]:
access_points = [4, 8, 10, 12, 16]
selected_ap_group = (10, 4, 12)

In [149]:
def _encode_ap_group(sharing_ap, selected_ap_group) -> Array: 
    ap_group = np.asarray(list(selected_ap_group) + [sharing_ap])
    print(ap_group)
    return (
        np.isin(
            np.asarray(access_points), 
            ap_group
        ).astype(np.int32)
    )

In [150]:
_encode_ap_group(sharing_ap=10, selected_ap_group=selected_ap_group)

[10  4 12 10]


array([1, 0, 1, 1, 0], dtype=int32)

In [180]:
associations = {
    i: list(range(0, 4))
    for i in range(4)
}

print(associations)

{0: [0, 1, 2, 3], 1: [0, 1, 2, 3], 2: [0, 1, 2, 3], 3: [0, 1, 2, 3]}


In [189]:
from itertools import combinations
for i, item in enumerate(combinations(list(range(3)), 2)):
    print(i, list(item))

0 [0, 1]
1 [0, 2]
2 [1, 2]
