In [23]:
from collections import defaultdict
from copy import deepcopy
from itertools import chain, combinations, product
from typing import Iterable, Iterator

import numpy as np
from reinforced_lib import RLib
from reinforced_lib.agents.deep import DQN

from mapc_cmab.agents.mapc_agent import MapcAgent

from mapc_cmab.agents.q_network import QNetwork_lv1
import optax 


In [24]:
n_ap = 3 

In [25]:

rl = RLib(
    agent_type=DQN,

    agent_params = {
        "q_network": QNetwork_lv1(n_actions=2**(n_ap - 1)), 

        "obs_space_shape": (2, ), 
        "act_space_size": 5, 

        "optimizer": optax.adam(1e-3), 

        "experience_replay_buffer_size": 1000,
        "experience_replay_batch_size": 32,
        "experience_replay_steps": 1,

        #contextual Bandit type
        "discount": 0.0, 

        "epsilon": 1.0, 
        "epsilon_decay": 0.995,
        "epsilon_min": 0.05,
    },
    no_ext_mode=True,
)

In [26]:
a = np.zeros(shape=(4, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
pairs = [[0, 1], [1, 3]]
a[pairs[0], pairs[1]] = 1

In [28]:
print(a)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
b = np.array([1, 2, 3, 4])
(b == 2).argmax()

aps = [0, 1]
stas = [2, 3]

b = np.zeros(shape=(4, 4))
b[aps, stas] = 1
b

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])