In [14]:
from flax import linen as nn 

import jax
import jax.numpy as jnp
import flax.linen as nn

# 1. Define the network as a class inheriting from nn.Module
class Network(nn.Module):
    @nn.compact
    def __call__(self, x):
        x = nn.Dense(64)(x)
        x = nn.relu(x)
        x = nn.Dense(64)(x)
        x = nn.relu(x)
        return nn.Dense(5)(x)

model = Network()

x = jnp.ones((1, 32))  # Example shape
key = jax.random.PRNGKey(0)
variables = model.init(key, x)
# 4. Run the model using model.apply()
output = model.apply(variables, x)


In [15]:
print(output.flatten())

[0.68671715 0.34483325 0.5633434  0.49640375 0.01801642]


In [16]:
import numpy as np 

rng = np.random.default_rng()
rng.normal([1, 2, 3, 4, 5, 6], 10)


array([ 0.07575254, -6.46337802,  6.49698346,  7.65259159, -0.75271443,
        3.98060189])

In [17]:
def action_to_ap_group(action, aps):
    return np.asarray(aps)[np.array(action).astype(bool)]

In [18]:
action_to_ap_group([0, 0, 0, 1, 1, 0], [4, 8, 12, 16, 20, 22])

array([16, 20])

In [19]:
np.array([10, 20, 30, 40])[np.array([True, False, False, True])]

array([10, 40])

In [24]:
np.array([[0, 1, 2, 2]]).squeeze(0)

array([0, 1, 2, 2])