In [ ]:
from flax import linen as nn 

import jax
import jax.numpy as jnp
import flax.linen as nn

# 1. Define the network as a class inheriting from nn.Module
class Network(nn.Module):
    @nn.compact
    def __call__(self, x):
        x = nn.Dense(64)(x)
        x = nn.relu(x)
        x = nn.Dense(64)(x)
        x = nn.relu(x)
        return nn.Dense(5)(x)

model = Network()

x = jnp.ones((1, 32))  # Example shape
key = jax.random.PRNGKey(0)
variables = model.init(key, x)
# 4. Run the model using model.apply()
output = model.apply(variables, x)


[[0.68671715 0.34483325 0.5633434  0.49640375 0.01801642]]


In [21]:
print(output.flatten())

[0.68671715 0.34483325 0.5633434  0.49640375 0.01801642]


In [38]:
import numpy as np 

rng = np.random.default_rng()
rng.normal([1, 2, 3, 4, 5, 6], 10)


array([-14.27130875,   7.17349911,  10.19488039,  -1.01652593,
        -0.456328  ,   9.50787771])